config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('phone_auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('aboutus/', views.AboutUsPageView.as_view(), name='aboutus'),
]

phone_auth/urls.py
from django.urls import path

from .views import (
    AddEmailView,
    AddPhoneView,
    PhoneChangePasswordDoneView,
    PhoneChangePasswordView,
    PhoneEmailVerificationConfirmView,
    PhoneEmailVerificationView,
    PhoneLoginView,
    PhoneLogoutView,
    PhonePasswordConfirmView,
    PhonePasswordResetCompleteView,
    PhonePasswordResetDoneView,
    PhonePasswordResetView,
    PhoneSignupView,
)

app_name = "phone_auth"

urlpatterns = [
    path("signup/", PhoneSignupView.as_view(), name="phone_signup"),
    path("login/", PhoneLoginView.as_view(), name="phone_login"),
    path("logout/", PhoneLogoutView.as_view(), name="phone_logout"),
    path(
        "password_reset/", PhonePasswordResetView.as_view(), name="phone_password_reset"
    ),
    path(
        "password_reset_done/",
        PhonePasswordResetDoneView.as_view(),
        name="phone_password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PhonePasswordConfirmView.as_view(),
        name="phone_password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        PhonePasswordResetCompleteView.as_view(),
        name="phone_password_reset_complete",
    ),
    path(
        "change_password/",
        PhoneChangePasswordView.as_view(),
        name="phone_change_password",
    ),
    path(
        "change_password_done/",
        PhoneChangePasswordDoneView.as_view(),
        name="phone_change_password_done",
    ),
    path(
        "user_verification/",
        PhoneEmailVerificationView.as_view(),
        name="phone_email_verification",
    ),
    path(
        "user_verification_confirm/<idb64>/<token>/",
        PhoneEmailVerificationConfirmView.as_view(),
        name="phone_email_verification_confirm",
    ),
    path(
        "phone/add/",
        AddPhoneView.as_view(),
        name="add_phone",
    ),
    path(
        "email/add/",
        AddEmailView.as_view(),
        name="add_email",
    ),
]

phone_auth/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse

# noinspection PyUnresolvedReferences
from phonenumber_field.modelfields import PhoneNumberField

User = get_user_model()


class PhoneNumber(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = PhoneNumberField(unique=True, blank=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return str(self.phone)
    


class EmailAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, blank=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email
    

phone_auth/forms.py
import uuid

from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.hashers import make_password
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError
from django.db import DatabaseError, IntegrityError, transaction
from django.db.models import Q
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

# noinspection PyUnresolvedReferences
from phonenumber_field.formfields import PhoneNumberField

from phone_auth.validators import validate_username

from . import app_settings
from .models import EmailAddress, PhoneNumber
from .signals import (
    reset_password_email,
    reset_password_phone,
    verify_email,
    verify_phone,
)
from .tokens import phone_token_generator

User = get_user_model()


class PhoneRegisterForm(forms.Form):
    """Form for user registration"""

    phone = PhoneNumberField()
    username = forms.CharField(
        required=app_settings.REGISTER_USERNAME_REQUIRED, validators=[validate_username]
    )
    email = forms.EmailField(required=app_settings.REGISTER_EMAIL_REQUIRED)
    #first_name = forms.CharField(required=app_settings.REGISTER_FNAME_REQUIRED)
    #last_name = forms.CharField(required=app_settings.REGISTER_LNAME_REQUIRED)
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(),
        required=app_settings.REGISTER_CONFIRM_PASSWORD_REQUIRED,
    )

    def clean(self):
        errors = {}
        if app_settings.REGISTER_CONFIRM_PASSWORD_REQUIRED:
            if self.cleaned_data.get("password") != self.cleaned_data.get(
                "confirm_password"
            ):
                errors["confirm_password"] = "Password didn't match"
        if self.cleaned_data.get("email", None) is not None:
            if EmailAddress.objects.filter(
                email__iexact=self.cleaned_data.get("email")
            ).exists():
                errors["email"] = "Email already exists"
        if self.cleaned_data.get("phone", None) is not None:
            if PhoneNumber.objects.filter(
                phone=self.cleaned_data.get("phone")
            ).exists():
                errors["phone"] = "Phone already exists"
        if self.cleaned_data.get("username", None) is not None:
            if User.objects.filter(
                username__exact=self.cleaned_data.get("username")
            ).exists():
                errors["username"] = "Username already exists"

        if errors:
            raise ValidationError(errors)

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get("password")
        user_data = dict(self.cleaned_data)
        if "phone" in user_data:
            user_data.pop("phone")
        if "confirm_password" in user_data:
            user_data.pop("confirm_password")
        user_instance = User(**user_data)

        try:
            password_validation.validate_password(password, user=user_instance)
        except ValidationError as error:
            self.add_error("password", error)

    def save(self):
        try:
            phone = self.cleaned_data.get("phone", None)
            if phone is not None:
                self.cleaned_data.pop("phone")

            if "confirm_password" in self.cleaned_data:
                self.cleaned_data.pop("confirm_password")

            username = self.cleaned_data.get("username")
            if not username:
                self.cleaned_data["username"] = uuid.uuid4().hex

            email = self.cleaned_data.get("email", None)

            self.cleaned_data["password"] = make_password(self.cleaned_data["password"])

            with transaction.atomic():
                user = User.objects.create(**self.cleaned_data)
                if phone is not None:
                    PhoneNumber.objects.create(user=user, phone=phone)
                if email is not None:
                    EmailAddress.objects.create(user=user, email=email)
        except DatabaseError as e:
            if "UNIQUE constraint" in e.args[0]:
                if "phone" in e.args[0]:
                    self.add_error("phone", "Phone already exists")
                if "username" in e.args[0]:
                    self.add_error("username", "Username already exists")
                if "email" in e.args[0]:
                    self.add_error("email", "Email already exists")


class PhoneLoginForm(forms.Form):
    """Form used for user login"""

    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(PhoneLoginForm, self).__init__(*args, **kwargs)


class EmailValidationForm(forms.Form):
    """Form to validate email field"""

    email = forms.EmailField()


class PhoneValidationForm(forms.Form):
    """Form to validate phone field"""

    phone = PhoneNumberField()


class UsernameValidationForm(forms.Form):
    """Form to validate username field"""

    username = forms.CharField(validators=[validate_username])


class PhonePasswordResetForm(forms.Form):
    """Checks if the user with provided email/phone exists.

    If provided email/phone exists, send reset_password_email/reset_password_phone
    signal with user and URL (relative_path that is one-time use only link
    to reset password) arguments.
    """

    login = forms.CharField()

    @staticmethod
    def get_users_and_method(login):
        lookup_obj = Q()

        is_phone = False
        if PhoneValidationForm({"phone": login}).is_valid():
            lookup_obj |= Q(phonenumber__phone=login)
            is_phone = True

        elif EmailValidationForm({"email": login}).is_valid():
            lookup_obj |= Q(emailaddress__email__iexact=login)

        else:
            return None, False

        try:
            user = User.objects.get(lookup_obj)
            return user, is_phone
        except User.DoesNotExist:
            return None, False

    def save(self):
        login = self.cleaned_data.get("login", None)
        if login is not None:
            user, is_phone = self.get_users_and_method(login)

            if user:
                url = reverse(
                    "phone_auth:phone_password_reset_confirm",
                    kwargs={
                        "uidb64": urlsafe_base64_encode(force_bytes(user.pk)),
                        "token": default_token_generator.make_token(user),
                    },
                )
                if is_phone:
                    reset_password_phone.send(
                        sender=self.__class__, user=user, url=url, phone=login
                    )
                else:
                    reset_password_email.send(
                        sender=self.__class__, user=user, url=url, email=login
                    )


class PhoneEmailVerificationForm(forms.Form):
    """
    Send verify_email/verify_phone signal with user instance
    and relative_url which is one-time use link to verify email/phone
    user requested to verify.
    """

    method = forms.CharField(max_length=5)
    pk = forms.IntegerField()

    def save(self, user):
        method = self.cleaned_data.get("method")
        pk = self.cleaned_data.get("pk")
        if method == "email":
            try:
                email_obj = EmailAddress.objects.get(user=user, pk=pk)
                if email_obj.is_verified:
                    return "Email already Verified"

                url = self._get_token_url(
                    email_obj=email_obj, phone_obj=None, user=user
                )
                verify_email.send(
                    sender=self.__class__,
                    user=user,
                    url=url,
                    email=email_obj.email,
                )
                return "Email Verification Sent"
            except EmailAddress.DoesNotExist:
                # In this case say email sent successfully
                # to avoid user enumeration attack
                pass
        elif method == "phone":
            try:
                phone_obj = PhoneNumber.objects.get(user=user, pk=pk)
                if phone_obj.is_verified:
                    return "Phone already Verified"

                url = self._get_token_url(
                    email_obj=None, phone_obj=phone_obj, user=user
                )
                verify_phone.send(
                    sender=self.__class__,
                    user=user,
                    url=url,
                    phone=phone_obj.phone.__str__(),
                )
                return "Phone Verification Sent"
            except PhoneNumber.DoesNotExist:
                pass

        return "Something Went Wrong"

    def _get_token_url(self, email_obj, phone_obj, user):
        token = phone_token_generator(
            email_address_obj=email_obj, phone_number_obj=phone_obj
        ).make_token(user)
        url = reverse(
            "phone_auth:phone_email_verification_confirm",
            kwargs={
                "idb64": self._get_email_phone_b64(email_obj, phone_obj),
                "token": token,
            },
        )
        return url

    @staticmethod
    def _get_email_phone_b64(email_obj, phone_obj):
        if email_obj is not None:
            return urlsafe_base64_encode(force_bytes(f"email{email_obj.pk}"))
        if phone_obj is not None:
            return urlsafe_base64_encode(force_bytes(f"phone{phone_obj.pk}"))


class PhoneLogoutForm(forms.Form):
    pass


class AddPhoneForm(forms.Form):
    """Form to add new phone number"""

    phone = PhoneNumberField(required=True)

    def save(self, user):
        try:
            phone = self.cleaned_data.get("phone")

templates/phone_auth/add_new_email.html
{% extends "_base.html" %}

{% block title_block %}
    Add Email
{% endblock title_block %}

{% block content %}
    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Add Email</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.email.errors }}
            <label for="id_email">
                Email:
            </label>
            <input type="email"
                   id="id_email"
                   name="email"
                   {% if form.email.value %}
                        value="{{ form.email.value }}"
                   {% endif %}
                   {% if form.email.field.required %}required{% endif %}>
        </div>

        <button type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/add_new_phone.html
{% extends "_base.html" %}

{% block title_block %}
    Add Phone
{% endblock title_block %}

{% block content %}
    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Add Phone</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.phone.errors }}
            <label for="id_phone">
                Phone:
            </label>
            <input type="tel"
                   id="id_phone"
                   name="phone"
                   {% if form.phone.value %}
                        value="{{ form.phone.value }}"
                   {% endif %}
                   {% if form.phone.field.required %}required{% endif %}>
        </div>

        <button type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/change_password.html
{% extends "_base.html" %}

{% block title_block %}
    Change Password
{% endblock title_block %}

{% block content %}
    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Change Password</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.old_password.errors }}
            <label for="id_old_password">
                Old Password:
            </label>
            <input type="password"
                   id="id_old_password"
                   name="{{ form.old_password.html_name }}"
                   {% if form.old_password.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.new_password1.errors }}
            <label for="id_new_password1">
                New Password:
            </label>
            <input type="password"
                   id="id_new_password1"
                   name="{{ form.new_password1.html_name }}"
                   {% if form.new_password1.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.new_password2.errors }}
            <label for="id_new_password2">
                Confirm Password:
            </label>
            <input type="password"
                   id="id_new_password2"
                   name="{{ form.new_password2.html_name }}"
                   {% if form.new_password2.field.required %}required{% endif %}>
        </div>

        <button class="phoneauth-button" type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/change_password_done.html
{% extends "_base.html" %}

{% block title_block %}
    Change Password Done
{% endblock title_block %}

{% block content %}
<div class="phoneauth-jumbotron">
    <div class="message">
        {% if title %}
            <h1>{{ title }}</h1>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/phone_auth/login.html
{% extends "_base.html" %}

{% block title_block %}
    Sign In
{% endblock title_block %}
    
{% block content %}
    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Sign In</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.login.errors }}
            <label for="id_login">
                Phone, Email or Username:
            </label>
            <input type="text"
                   id="id_login"
                   name="{{ form.login.html_name }}"
                   {% if form.login.value %}
                        value="{{ form.login.value }}"
                   {% endif %}
                   {% if form.login.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.password.errors }}
            <label for="id_password">
                Password:
            </label>
            <input type="password"
                   id="id_password"
                   name="{{ form.password.html_name }}"
                   {% if form.password.field.required %}required{% endif %}>
        </div>

        <button type="submit">Submit</button>
    </form>
    <div class="dpa-help-text">
        <p>
            Don't have an account? <a href="{% url 'phone_auth:phone_signup' %}">Sign up</a>
        </p> 
        <a href="{% url 'phone_auth:phone_password_reset' %}">Forgot Password?</a>
    </div>
</div>
{% endblock content %}

templates/phone_auth/logout.html
{% extends "_base.html" %}

{% block title_block %}
    Logout
{% endblock title_block %}

{% block content %}
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Are you sure you want to logout?</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/password_reset.html
{% extends "_base.html" %}

{% block title_block %}
    Reset Password
{% endblock title_block %}
    
{% block content %}

    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Reset Password</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.login.errors }}
            <label for="id_login">
                Phone, Email or Username:
            </label>
            <input type="text"
                   id="id_login"
                   name="{{ form.login.html_name }}"
                   {% if form.login.value %}
                        value="{{ form.login.value }}"
                   {% endif %}
                   {% if form.login.field.required %}required{% endif %}>
        </div>

        <button type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/password_reset_complete.html
{% extends "_base.html" %}

{% block title_block %}
    Password Reset Completed
{% endblock title_block %}

{% block content %}
<div class="phoneauth-jumbotron">
    <div class="message">
        {% if title %}
            <h1>{{ title }}</h1>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/phone_auth/password_reset_confirm.html
{% extends "_base.html" %}

{% block title_block %}
    Set Password
{% endblock title_block %}

{% block content %}

    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Set Password</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.new_password1.errors }}
            <label for="id_new_password1">
                New Password:
            </label>
            <input type="password"
                   id="id_new_password1"
                   name="{{ form.new_password1.html_name }}"
                   {% if form.new_password1.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.new_password2.errors }}
            <label for="id_new_password2">
                Confirm Password:
            </label>
            <input type="password"
                   id="id_new_password2"
                   name="{{ form.new_password2.html_name }}"
                   {% if form.new_password2.field.required %}required{% endif %}>
        </div>

        <button type="submit">Submit</button>
    </form>
</div>
{% endblock content %}

templates/phone_auth/password_reset_done.html
{% extends "_base.html" %}

{% block title_block %}
    Password Reset Done
{% endblock title_block %}
    
{% block content %}
<div class="phoneauth-jumbotron">
    <div class="message">
        {% if title %}
            <h1>{{ title }}</h1>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/phone_auth/phone_and_email_verification.html
{% extends "_base.html" %}

{% block title_block %}
User Verification
{% endblock title_block %}

{% block content %}

<div class="phoneauth-jumbotron">
    <div class="message">
        {% if title %}
            <h1>{{ title }}</h1>
        {% endif %}
    </div>

    <div class="dpa-table-title">
        <h3>Email Addresses</h3>
        <a href="{% url 'phone_auth:add_email' %}">+ Add New</a>
    </div>
    <div class="dpa-table">
        <div class="dpa-row header">
            <div class="dpa-cell">
                Email Address
            </div>
            <div class="dpa-cell">
                Status
            </div>
        </div>
        {% for email_obj in email_addresses %}
        <div class="dpa-row">
            <div class="dpa-cell">
                {{ email_obj.email }}
            </div>
            <div class="dpa-cell">
                <form method="POST">
                    {% if email_obj.is_verified %}
                    <p>Verified</p>
                    {% else %}
                    {% csrf_token %}
                    <input type="hidden" name="method" value="email">
                    <input type="hidden" name="pk" value="{{ email_obj.pk }}">
                    <input class="dpa-cell-btn" type="submit" value="Verify">
                    {% endif %}
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="dpa-table-title">
        <h3>Phone Numbers</h3>
        <a href="{% url 'phone_auth:add_phone' %}">+ Add New</a>
    </div>
    <div class="dpa-table">
        <div class="dpa-row header">
            <div class="dpa-cell">
                Phone Number
            </div>
            <div class="dpa-cell">
                Status
            </div>
        </div>
        {% for phone_obj in phone_numbers %}
        <div class="dpa-row">
            <div class="dpa-cell">
                {{ phone_obj.phone }}
            </div>
            <div class="dpa-cell">
                {% if phone_obj.is_verified %}
                <p>Verified</p>
                {% else %}
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="method" value="phone">
                    <input type="hidden" name="pk" value="{{ phone_obj.pk }}">
                    <input class="dpa-cell-btn" type="submit" value="Verify">
                </form>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/phone_auth/phone_email_verification_confirm.html
{% extends "_base.html" %}

{% block title_block %}
    User Verification
{% endblock title_block %}

{% block content %}
<div class="phoneauth-jumbotron">
    <div class="message">
        <h1>{{ title }}</h1>
    </div>
</div>
{% endblock content %}

templates/phone_auth/profile.html
{% extends '_base.html' %}

{% block title_block %}
<h1>Profile</h1>
{% endblock title_block %}

templates/phone_auth/signup.html
{% extends "_base.html" %}

{% block title_block %}
    Sign Up
{% endblock title_block %}

{% block content %}

    <!--suppress HtmlUnknownAttribute -->
<div class="phoneauthform">
    <h3 class="phoneauthform-title">Sign Up</h3>
    <form class="phoneauthform-content" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="fieldWrapper">
            {{ form.first_name.errors }}
            <label for="id_first_name">
                First Name{% if form.first_name.field.required %}*{% endif %}:
            </label>
            <input type="text"
                   id="id_first_name"
                   name="{{ form.first_name.html_name }}"
                   {% if form.first_name.value %}
                        value="{{ form.first_name.value }}"
                   {% endif %}
                   {% if form.first_name.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.last_name.errors }}
            <label for="id_last_name">
                Last Name{% if form.last_name.field.required %}*{% endif %}:
            </label>
            <input type="text"
                   id="id_last_name"
                   name="{{ form.last_name.html_name }}"
                   {% if form.last_name.value %}
                        value="{{ form.last_name.value }}"
                   {% endif %}
                   {% if form.last_name.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.username.errors }}
            <label for="id_username">
                Username{% if form.username.field.required %}*{% endif %}:
            </label>
            <input type="text"
                   id="id_username"
                   name="{{ form.username.html_name }}"
                   {% if form.username.value %}
                        value="{{ form.username.value }}"
                   {% endif %}
                   {% if form.username.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.email.errors }}
            <label for="id_email">
                Email{% if form.email.field.required %}*{% endif %}:
            </label>
            <input type="email"
                   id="id_email"
                   name="{{ form.email.html_name }}"
                   {% if form.email.value %}
                        value="{{ form.email.value }}"
                   {% endif %}
                   {% if form.email.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.phone.errors }}
            <label for="id_phone">
                Phone{% if form.phone.field.required %}*{% endif %}:
            </label>
            <input type="tel"
                   id="id_phone"
                   name="{{ form.phone.html_name }}"
                   {% if form.phone.value %}
                        value="{{ form.phone.value }}"
                   {% endif %}
                   {% if form.phone.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.password.errors }}
            <label for="id_password">
                Password{% if form.password.field.required %}*{% endif %}:
            </label>
            <input type="password"
                   id="id_password"
                   name="{{ form.password.html_name }}"
                   {% if form.password.field.required %}required{% endif %}>
        </div>

        <div class="fieldWrapper">
            {{ form.confirm_password.errors }}
            <label for="id_confirm_password">
                Confirm Password{% if form.confirm_password.field.required %}*{% endif %}:
            </label>
            <input type="password"
                   id="id_confirm_password"
                   name="{{ form.confirm_password.html_name }}"
                   {% if form.confirm_password.field.required %}required{% endif %}>
        </div>

        <button class="phoneauth-button" type="submit">Submit</button>
    </form>
    <div class="dpa-help-text">
        <p>
            Have an account? <a href="{% url 'phone_auth:phone_login' %}">Log in</a>
        </p>
    </div>
</div>
{% endblock content %}