config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('phone_auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('aboutus/', views.AboutUsPageView.as_view(), name='aboutus'),
]

phone_auth/urls.py
from django.urls import path

from .views import (
    AddEmailView,
    AddPhoneView,
    PhoneChangePasswordDoneView,
    PhoneChangePasswordView,
    PhoneEmailVerificationConfirmView,
    PhoneEmailVerificationView,
    PhoneLoginView,
    PhoneLogoutView,
    PhonePasswordConfirmView,
    PhonePasswordResetCompleteView,
    PhonePasswordResetDoneView,
    PhonePasswordResetView,
    PhoneSignupView,
)

app_name = "phone_auth"

urlpatterns = [
    path("signup/", PhoneSignupView.as_view(), name="phone_signup"),
    path("login/", PhoneLoginView.as_view(), name="phone_login"),
    path("logout/", PhoneLogoutView.as_view(), name="phone_logout"),
    path(
        "password_reset/", PhonePasswordResetView.as_view(), name="phone_password_reset"
    ),
    path(
        "password_reset_done/",
        PhonePasswordResetDoneView.as_view(),
        name="phone_password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PhonePasswordConfirmView.as_view(),
        name="phone_password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        PhonePasswordResetCompleteView.as_view(),
        name="phone_password_reset_complete",
    ),
    path(
        "change_password/",
        PhoneChangePasswordView.as_view(),
        name="phone_change_password",
    ),
    path(
        "change_password_done/",
        PhoneChangePasswordDoneView.as_view(),
        name="phone_change_password_done",
    ),
    path(
        "user_verification/",
        PhoneEmailVerificationView.as_view(),
        name="phone_email_verification",
    ),
    path(
        "user_verification_confirm/<idb64>/<token>/",
        PhoneEmailVerificationConfirmView.as_view(),
        name="phone_email_verification_confirm",
    ),
    path(
        "phone/add/",
        AddPhoneView.as_view(),
        name="add_phone",
    ),
    path(
        "email/add/",
        AddEmailView.as_view(),
        name="add_email",
    ),
]

templates/_base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title_block  %}
            Base Title
        {% endblock title_block  %}
    </title>

    <link rel="stylesheet" href="{% static 'phone_auth/css/style.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
    <h1>Hello {{ user.username }}</h1> | <a href="{% url 'phone_auth:phone_logout' %}">logout</a>
    {% else %}
        <a href="{% url 'phone_auth:phone_login' %}">login</a> | <a href="{% url 'phone_auth:phone_signup' %}">sign up</a>
    {% endif %}
    
    {% block content  %}
        <!-- Base body -->
    {% endblock content  %}
</body>
</html>

templates/home.html
{% extends '_base.html' %}

{% block content %}

<h1>Home</h1>

{% endblock content %}